---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[dotpromo-postgresql-box::default]
      - recipe[minitest-handler]
