---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.8.1'
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[dotpromo-postgresql-box::default]
      - recipe[minitest-handler]
